version: '2'
services:

  app:
    build: .
    container_name: php-rest-app
    volumes:
      - ./app:/usr/src/app

  nginx:
    image: nginx:alpine
    container_name: php-rest-nginx
    volumes_from:
      - app
    links:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=api.dev

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: php-rest-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

